Fix ESAPI Python types and comments, and many misspellings
tpm2-software/tpm2-pytss pull request #259
Opened 2021-11-09 15:05 UTC by niooss-ledger

In ESAPI:

- Use `Optional` or `Union[..., None]` where a variable can be `None`.
- Fix the description of some functions, which was probably copy-pasted from other ones.
- Use `ESYS_TR.OWNER` instead of `TPM2_RH_OWNER`, and also for `ENDORSEMENT` and `PLATFORM`
- Uniformize `ESYS_TR.PLATFORM+{PP}` notation (for "Physical Presence")

While at it, fix many other misspellings in other files.

2021-11-09 18:08 UTC, williamcroberts requested changes
minor nit, rather than fixing the spelling on clone instructions, lets fix the instructions since they are outdated.

2021-11-09 18:08 UTC, williamcroberts commented on tpm2_pytss/ESAPI.py
> +        self._tcti: Optional[TCTI] = tcti
interesting, didn't know you could type hint instance variables.

2021-11-10 10:27 UTC, niooss-ledger commented on HACKING.md
> +You need to clone recursive so that you will get the swig interface files as a
Indeed. I removed the sentences.

2021-11-10 15:15 UTC, niooss-ledger commented
> @niooss-ledger can you reformat your patch, looks like black is flunking it. Make sure you have the right version:
> 
> ```
> black, version 19.10b0
> ```

Done. The diff was:

```diff
diff --git a/tpm2_pytss/ESAPI.py b/tpm2_pytss/ESAPI.py
index 48a6370cc81d..9303401aa7a6 100644
--- a/tpm2_pytss/ESAPI.py
+++ b/tpm2_pytss/ESAPI.py
@@ -5126,9 +5126,7 @@ class ESAPI:
         """
 
         _check_handle_type(
-            auth_handle,
-            "auth_handle",
-            expected=(ESYS_TR.PLATFORM, ESYS_TR.LOCKOUT),
+            auth_handle, "auth_handle", expected=(ESYS_TR.PLATFORM, ESYS_TR.LOCKOUT)
         )
 
         _check_handle_type(session1, "session1")
@@ -5168,9 +5166,7 @@ class ESAPI:
         TPM Command: TPM2_ClearControl
         """
 
-        _check_handle_type(
-            auth, "auth", expected=(ESYS_TR.PLATFORM, ESYS_TR.LOCKOUT)
-        )
+        _check_handle_type(auth, "auth", expected=(ESYS_TR.PLATFORM, ESYS_TR.LOCKOUT))
 
         _check_handle_type(session1, "session1")
         _check_handle_type(session2, "session2")
```

2021-11-11 17:19 UTC, merged