Corrected typo in README. Added note about required libraries to READ…
tpm2-software/tpm2-pytss pull request #348
Opened 2022-04-23 08:05 UTC by iolivergithub

…ME and install.rst

Signed-off-by: Ian <ian.justin.oliver@gmail.com>

2022-04-25 15:22 UTC, whooo requested changes

2022-05-09 21:57 UTC, whooo commented on README.md
> +
Then I think they need to be very clear (for example include build-essential for Debian-based systems) and include instructions for multiple common distributions, or be very generic

2022-10-25 20:10 UTC, williamcroberts commented
@iolivergithub and @whooo what should I do with the PR?

2022-10-26 06:17 UTC, iolivergithub commented
I didn't know it was still open.  CLose it I think, there were conflicts
with the pull.  I'll redo these when I have time

Ian

On Tue, 25 Oct 2022 at 23:10, William Roberts ***@***.***>
wrote:

> @iolivergithub <https://github.com/iolivergithub> and @whooo
> <https://github.com/whooo> what should I do with the PR?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/tpm2-software/tpm2-pytss/pull/348#issuecomment-1291080460>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHKY2MIEV66Y7PCIW6BXXRTWFA5ENANCNFSM5UELIYTQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-26 15:02 UTC, closed without merging